-- Marketing Automation Tables
-- Support for automated campaigns based on RFM segmentation

-- ============================================================================
-- automation_queue: Scheduled automation actions
-- ============================================================================

CREATE TABLE IF NOT EXISTS automation_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id VARCHAR(100) NOT NULL,
  contact_id UUID NOT NULL REFERENCES scanned_contacts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  action_type VARCHAR(50) NOT NULL,
  action_data JSONB NOT NULL DEFAULT '{}',

  execute_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executing', 'completed', 'failed', 'cancelled')),

  executed_at TIMESTAMP WITH TIME ZONE,
  error TEXT,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_automation_queue_execute_at ON automation_queue(execute_at) WHERE status = 'pending';
CREATE INDEX idx_automation_queue_contact_id ON automation_queue(contact_id);
CREATE INDEX idx_automation_queue_user_id ON automation_queue(user_id);
CREATE INDEX idx_automation_queue_status ON automation_queue(status);
CREATE INDEX idx_automation_queue_rule_id ON automation_queue(rule_id);

-- ============================================================================
-- automation_logs: Execution history
-- ============================================================================

CREATE TABLE IF NOT EXISTS automation_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id VARCHAR(100) NOT NULL,
  contact_id UUID NOT NULL REFERENCES scanned_contacts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executing', 'completed', 'failed')),
  actions JSONB NOT NULL DEFAULT '[]',

  error TEXT,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,

  -- Metrics
  sent_count INTEGER DEFAULT 0,
  opened_count INTEGER DEFAULT 0,
  clicked_count INTEGER DEFAULT 0,
  converted BOOLEAN DEFAULT false,
  revenue NUMERIC(10, 2) DEFAULT 0
);

-- Indexes
CREATE INDEX idx_automation_logs_rule_id ON automation_logs(rule_id);
CREATE INDEX idx_automation_logs_contact_id ON automation_logs(contact_id);
CREATE INDEX idx_automation_logs_user_id ON automation_logs(user_id);
CREATE INDEX idx_automation_logs_created_at ON automation_logs(created_at DESC);
CREATE INDEX idx_automation_logs_status ON automation_logs(status);

-- ============================================================================
-- crm_tasks: Tasks generated by automation
-- ============================================================================

CREATE TABLE IF NOT EXISTS crm_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id UUID NOT NULL REFERENCES scanned_contacts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_to UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  task_type VARCHAR(50) NOT NULL CHECK (task_type IN ('call', 'email', 'meeting', 'follow_up', 'assignment', 'general')),
  priority VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),

  title TEXT NOT NULL,
  description TEXT,

  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),

  due_date TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Metadata
  metadata JSONB DEFAULT '{}'
);

-- Indexes
CREATE INDEX idx_crm_tasks_contact_id ON crm_tasks(contact_id);
CREATE INDEX idx_crm_tasks_user_id ON crm_tasks(user_id);
CREATE INDEX idx_crm_tasks_assigned_to ON crm_tasks(assigned_to);
CREATE INDEX idx_crm_tasks_status ON crm_tasks(status);
CREATE INDEX idx_crm_tasks_priority ON crm_tasks(priority);
CREATE INDEX idx_crm_tasks_due_date ON crm_tasks(due_date) WHERE status != 'completed';

-- ============================================================================
-- automation_analytics: Campaign performance metrics
-- ============================================================================

CREATE TABLE IF NOT EXISTS automation_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id VARCHAR(100) NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  period_start DATE NOT NULL,
  period_end DATE NOT NULL,

  -- Campaign metrics
  sent_count INTEGER DEFAULT 0,
  delivered_count INTEGER DEFAULT 0,
  opened_count INTEGER DEFAULT 0,
  clicked_count INTEGER DEFAULT 0,
  converted_count INTEGER DEFAULT 0,

  -- Rates (calculated)
  open_rate NUMERIC(5, 4) DEFAULT 0,
  click_rate NUMERIC(5, 4) DEFAULT 0,
  conversion_rate NUMERIC(5, 4) DEFAULT 0,

  -- Revenue
  total_revenue NUMERIC(12, 2) DEFAULT 0,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_automation_analytics_rule_id ON automation_analytics(rule_id);
CREATE INDEX idx_automation_analytics_user_id ON automation_analytics(user_id);
CREATE INDEX idx_automation_analytics_period ON automation_analytics(period_start, period_end);

-- Unique constraint for one record per rule per period
CREATE UNIQUE INDEX idx_automation_analytics_unique ON automation_analytics(rule_id, user_id, period_start);

-- ============================================================================
-- RFM segment history: Track segment changes over time
-- ============================================================================

CREATE TABLE IF NOT EXISTS rfm_segment_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id UUID NOT NULL REFERENCES scanned_contacts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  segment VARCHAR(50) NOT NULL,
  r_score INTEGER NOT NULL CHECK (r_score >= 1 AND r_score <= 5),
  f_score INTEGER NOT NULL CHECK (f_score >= 1 AND f_score <= 5),
  m_score INTEGER NOT NULL CHECK (m_score >= 1 AND m_score <= 5),

  -- Stats at time of segment calculation
  total_revenue NUMERIC(12, 2),
  total_orders INTEGER,
  days_since_last_order INTEGER,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_rfm_history_contact_id ON rfm_segment_history(contact_id);
CREATE INDEX idx_rfm_history_user_id ON rfm_segment_history(user_id);
CREATE INDEX idx_rfm_history_segment ON rfm_segment_history(segment);
CREATE INDEX idx_rfm_history_created_at ON rfm_segment_history(created_at DESC);

-- ============================================================================
-- Enable RLS
-- ============================================================================

ALTER TABLE automation_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfm_segment_history ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS Policies
-- ============================================================================

-- automation_queue policies
CREATE POLICY "Users can view own automation queue" ON automation_queue
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can insert own automation queue" ON automation_queue
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own automation queue" ON automation_queue
  FOR UPDATE USING (user_id = auth.uid());

CREATE POLICY "Users can delete own automation queue" ON automation_queue
  FOR DELETE USING (user_id = auth.uid());

-- automation_logs policies
CREATE POLICY "Users can view own automation logs" ON automation_logs
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can insert own automation logs" ON automation_logs
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own automation logs" ON automation_logs
  FOR UPDATE USING (user_id = auth.uid());

-- crm_tasks policies
CREATE POLICY "Users can view own tasks or assigned tasks" ON crm_tasks
  FOR SELECT USING (user_id = auth.uid() OR assigned_to = auth.uid());

CREATE POLICY "Users can create tasks" ON crm_tasks
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own tasks or assigned tasks" ON crm_tasks
  FOR UPDATE USING (user_id = auth.uid() OR assigned_to = auth.uid());

CREATE POLICY "Users can delete own tasks" ON crm_tasks
  FOR DELETE USING (user_id = auth.uid());

-- automation_analytics policies
CREATE POLICY "Users can view own analytics" ON automation_analytics
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can insert own analytics" ON automation_analytics
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- rfm_segment_history policies
CREATE POLICY "Users can view own RFM history" ON rfm_segment_history
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can insert own RFM history" ON rfm_segment_history
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- ============================================================================
-- Functions
-- ============================================================================

-- Function to process pending automation queue items
CREATE OR REPLACE FUNCTION process_automation_queue()
RETURNS TABLE(processed_count INTEGER) AS $$
DECLARE
  processed INTEGER := 0;
  queue_item RECORD;
BEGIN
  -- Get all pending items that should be executed now
  FOR queue_item IN
    SELECT * FROM automation_queue
    WHERE status = 'pending'
    AND execute_at <= NOW()
    ORDER BY execute_at ASC
    LIMIT 100  -- Process in batches
  LOOP
    -- Mark as executing
    UPDATE automation_queue
    SET status = 'executing', updated_at = NOW()
    WHERE id = queue_item.id;

    -- In production, this would trigger actual execution
    -- For now, just mark as completed
    UPDATE automation_queue
    SET status = 'completed',
        executed_at = NOW(),
        updated_at = NOW()
    WHERE id = queue_item.id;

    processed := processed + 1;
  END LOOP;

  RETURN QUERY SELECT processed;
END;
$$ LANGUAGE plpgsql;

-- Function to track RFM segment changes and trigger automation
CREATE OR REPLACE FUNCTION track_rfm_segment_change()
RETURNS TRIGGER AS $$
DECLARE
  previous_segment VARCHAR(50);
  new_segment VARCHAR(50);
BEGIN
  -- Get previous segment from history
  SELECT segment INTO previous_segment
  FROM rfm_segment_history
  WHERE contact_id = NEW.id
  ORDER BY created_at DESC
  LIMIT 1;

  -- Calculate new segment (simplified - actual calculation in app)
  new_segment := NEW.tags[array_position(NEW.tags, 'segment_')];  -- Placeholder

  -- If segment changed, log it
  IF previous_segment IS DISTINCT FROM new_segment THEN
    -- Insert into history
    INSERT INTO rfm_segment_history (contact_id, user_id, segment, r_score, f_score, m_score)
    VALUES (NEW.id, NEW.user_id, new_segment, 0, 0, 0);  -- Scores calculated in app

    -- Trigger automation would happen in application code
    -- This is just the database trigger for logging
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to scanned_contacts table
CREATE TRIGGER track_contact_segment_changes
  AFTER UPDATE ON scanned_contacts
  FOR EACH ROW
  EXECUTE FUNCTION track_rfm_segment_change();

-- Function to calculate automation campaign ROI
CREATE OR REPLACE FUNCTION calculate_campaign_roi(
  p_rule_id VARCHAR(100),
  p_user_id UUID,
  p_period_days INTEGER DEFAULT 30
)
RETURNS TABLE(
  sent_count BIGINT,
  opened_count BIGINT,
  clicked_count BIGINT,
  converted_count BIGINT,
  open_rate NUMERIC,
  click_rate NUMERIC,
  conversion_rate NUMERIC,
  total_revenue NUMERIC,
  estimated_cost NUMERIC,
  roi_percent NUMERIC
) AS $$
DECLARE
  email_cost CONSTANT NUMERIC := 50;  -- 50 FCFA per email
BEGIN
  RETURN QUERY
  WITH campaign_stats AS (
    SELECT
      COUNT(*)::BIGINT as sent,
      COUNT(*) FILTER (WHERE opened_count > 0)::BIGINT as opened,
      COUNT(*) FILTER (WHERE clicked_count > 0)::BIGINT as clicked,
      COUNT(*) FILTER (WHERE converted)::BIGINT as converted,
      COALESCE(SUM(revenue), 0) as revenue
    FROM automation_logs
    WHERE rule_id = p_rule_id
      AND user_id = p_user_id
      AND created_at >= NOW() - INTERVAL '1 day' * p_period_days
  )
  SELECT
    sent,
    opened,
    clicked,
    converted,
    CASE WHEN sent > 0 THEN ROUND((opened::NUMERIC / sent::NUMERIC) * 100, 2) ELSE 0 END as open_rate,
    CASE WHEN sent > 0 THEN ROUND((clicked::NUMERIC / sent::NUMERIC) * 100, 2) ELSE 0 END as click_rate,
    CASE WHEN sent > 0 THEN ROUND((converted::NUMERIC / sent::NUMERIC) * 100, 2) ELSE 0 END as conversion_rate,
    revenue,
    sent * email_cost as cost,
    CASE WHEN sent * email_cost > 0
      THEN ROUND(((revenue - (sent * email_cost)) / (sent * email_cost)) * 100, 2)
      ELSE 0
    END as roi
  FROM campaign_stats;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE automation_queue IS 'Queue of scheduled automation actions to be executed';
COMMENT ON TABLE automation_logs IS 'Execution history and analytics for automation rules';
COMMENT ON TABLE crm_tasks IS 'Tasks generated by automation or manually created for CRM workflows';
COMMENT ON TABLE automation_analytics IS 'Aggregated analytics for automation campaigns by period';
COMMENT ON TABLE rfm_segment_history IS 'Historical tracking of RFM segment changes for contacts';

COMMENT ON FUNCTION process_automation_queue() IS 'Process pending automation queue items (call from cron job)';
COMMENT ON FUNCTION calculate_campaign_roi(VARCHAR, UUID, INTEGER) IS 'Calculate ROI metrics for an automation campaign';
